name: Pylint

on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch:
    inputs: {}

jobs:
  pylint:
    strategy:
      matrix:
        include:
        - { tests-types: "E", ignore-failures: false }     # Errors
        - { tests-types: "W", ignore-failures: false }     # Warnings
        - { tests-types: "WPS", ignore-failures: true }    # wemake-python-styleguide
        - { tests-types: "N", ignore-failures: true }      # Naming
        - { tests-types: "D,DAR", ignore-failures: true }  # Docstrings
        - { tests-types: "S", ignore-failures: true }      # Security
        - { tests-types: "B,C4,T,D,E80,RST,P,C90,F", ignore-failures: false }  # All the rest
      fail-fast: false

    name: Pylint ({{ matrix.tests-types }}, warn-only={{ matrix.ignore-failures }})
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3.0.2

    - name: Install Poetry
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pipx install poetry
        poetry --version

    - name: Setup Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.9
        architecture: x64
        cache: 'poetry'

    - name: Upgrade pip
      env:
        PIP_CONSTRAINT: .github/workflows/constraints.txt
      run: |
        pip install pip
        pip --version

    - name: Install Dependencies
      run: |
        poetry env use 3.9
        poetry install

    - name: Run pylint
      run: |
        flake8 --select={{ matrix.test-types }}
      continue-on-error: {{ matrix.ignore-failures }}

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3.0.2

    - name: Install Poetry
      run: |
        pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
        poetry --version

    - name: Set up Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: '3.9'
        cache: 'poetry'

    - name: Upgrade pip
      run: |
        pip install --constraint=.github/workflows/constraints.txt pip
        pip --version

    - name: Download coverage data
      uses: actions/download-artifact@v3.0.0
      with:
        name: coverage-data

    - name: Install Dependencies
      run: |
        poetry env use "3.9"
        poetry install

    - name: Combine coverage data and display human readable report
      run: |
        poetry run coverage combine
        poetry run coverage report --show-missing

    - name: Create coverage report
      run: |
        poetry run coverage xml

    - name: Upload coverage report
      uses: codecov/codecov-action@v3.1.0
